# version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: salgalina/foodgram_backend:latest
    restart: always
    volumes:
      - /foodgram-project-react/data/:/backend/data/
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: salgalina/foodgram_frontend:latest
    volumes:
      - /foodgram-project-react/frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    # network_mode: 'host'
    volumes:
      - /foodgram-project-react/static:/var/html/static/
      - media_value:/var/html/media/
      - /foodgram-project-react/infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - /foodgram-project-react/frontend/build:/usr/share/nginx/html/
      - /foodgram-project-react/docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
